version: '3.3'
services:
    test:
        network_mode: host
        build: .
        shm_size: "2g"
        environment:
            TEST_SUITE: "SubmissionPage"
            ENV: "${ENV}"
            ADMIN_HOURLY_URL:     "${ADMIN_HOURLY_URL}"
            ADMIN_EMAIL:          "${ADMIN_EMAIL}"
            ADMIN_PWD:            "${ADMIN_PWD}"
            ADMIN_CODE:           "${ADMIN_CODE}"
            DELAY_TIMEOUT: 20
            DISPLAY_WIDTH: 1440
            DISPLAY_HEIGHT: 1080
        volumes: [
           "$PWD/test_suites:/test_suites",
           "$PWD/scripts:/scripts",
           "$PWD/reports:/reports",
           "$PWD/resources:/resources",
           "$PWD/env:/env",
        ]