*** Variables ***
${TITTLE_SUBMISSION}                    xpath=//div[@class='header']//span[contains(text(),'Submissions')]
${CREATE_SUBMISSION}                    xpath=//button[@aria-label='New Submission']
${POLICY_START_DATE_POP}                xpath=//button[@class="DateTimePicker_button__aYkyZ DateTimePickerField_button__2Tqbt"]
${POLICY_START_DATE_SELECT}             xpath=(//button[@class="CalendarGrid_day__Q33aU"])[6]
${NAME_OF_BUSINESS_TEXT}                xpath=//input[@class='UnderlineBasicInput_input__YARch']
${FEIN_TEXT}                            xpath=//input[@class='MaskTextField_input__9A934']
${SAVE_SUBMISSION}                      xpath=//button[@aria-label='Continue']
${TEMP_VALIDATION}                      xpath=//div[@class='QuoteDetailsHeader_iconWrapper__wCzKc']//*[name()='svg']
${MODAL_SUBMISSION}                     xpath=//div[@class='Dialog_dialog__DT-Qt NewSubmissionDialogButton_dialog__FZoRq']//div[@class='DialogHeader_header__-NB3s']